[package]
name = "mac_address_service"
version = "0.1.0"
edition = "2021"

[dependencies]
mac_address = "1.1"
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
if-addrs = "0.10.1"


